[package]
name = "qmllsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.17.0"
lsp-types = "0.93.0"
tokio = { version = "1.18.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.11"
tree-sitter = "0.20.7"
tree_sitter_qml = { path = "tree_sitter_qml" }
